"""empty message

Revision ID: 2e45fc811623
Revises: ea230d13f765
Create Date: 2022-09-16 19:28:47.801917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e45fc811623'
down_revision = 'ea230d13f765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'description')
    # ### end Alembic commands ###
