"""empty message

Revision ID: a6d2fd0ef323
Revises: efad9ac49c59
Create Date: 2022-09-16 19:39:11.905109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d2fd0ef323'
down_revision = 'efad9ac49c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'clients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('clients', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
