"""empty message

Revision ID: efad9ac49c59
Revises: 2eff9543face
Create Date: 2022-09-16 19:12:59.526768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efad9ac49c59'
down_revision = '2eff9543face'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'service', 'user', ['user_id'], ['id'])
    op.drop_column('service', 'provider_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_column('service', 'user_id')
    # ### end Alembic commands ###
